proxies:
- name: 🇭🇰香港 01 | @zmxooo 01 | @zmxooo
  server: 202.146.222.41
  type: hysteria2
  port: 443
- name: 🇭🇰香港 02 | @zmxooo 01 | @zmxooo
  server: 202.146.222.13
  type: hysteria2
  port: 443
- name: 🇭🇰香港 03 | @zmxooo 01 | @zmxooo
  server: 202.146.222.93
  type: hysteria2
  port: 443
- name: 🇭🇰香港 04 | @zmxooo 01 | @zmxooo
  server: 202.146.222.89
  type: hysteria2
  port: 443
- name: 🇭🇰香港 05 | @zmxooo 01 | @zmxooo
  server: 202.146.222.11
  type: hysteria2
  port: 443
- name: 🇭🇰香港 06 | @zmxooo 01 | @zmxooo
  server: 202.146.222.45
  type: hysteria2
  port: 443
- name: 🇭🇰香港 07 | @zmxooo 01 | @zmxooo
  server: 202.146.222.5
  type: hysteria2
  port: 443
- name: 🇭🇰香港 08 | @zmxooo 01 | @zmxooo
  server: 202.146.222.1
  type: hysteria2
  port: 443
- name: 🇭🇰香港 09 | @zmxooo 01 | @zmxooo
  server: 202.146.222.15
  type: hysteria2
  port: 443
- name: 🇹🇼台湾 10 | @zmxooo 01 | @zmxooo
  server: 45.132.226.177
  type: hysteria2
  port: 443
- name: 🇹🇼台湾 11 | @zmxooo 01 | @zmxooo
  server: 45.132.226.161
  type: hysteria2
  port: 443
- name: 🇹🇼台湾 12 | @zmxooo 01 | @zmxooo
  server: 45.132.226.153
  type: hysteria2
  port: 443
- name: 🇭🇰香港 28 | @zmxooo 01 | @zmxooo
  server: 202.146.222.11
  type: ss
  port: 443
- name: 🇭🇰香港 29 | @zmxooo 01 | @zmxooo
  server: 202.146.222.5
  type: ss
  port: 443
- name: 🇭🇰香港 30 | @zmxooo 01 | @zmxooo
  server: 202.146.222.1
  type: ss
  port: 443
- name: 🇭🇰香港 31 | @zmxooo 01 | @zmxooo
  server: 202.146.222.15
  type: ss
  port: 443
- name: 🇭🇰香港 32 | @zmxooo 01 | @zmxooo
  server: 202.146.222.13
  type: ss
  port: 443
- name: 🇭🇰香港 33 | @zmxooo 01 | @zmxooo
  server: 202.146.222.93
  type: ss
  port: 443
- name: 🇭🇰香港 34 | @zmxooo 01 | @zmxooo
  server: 202.146.222.89
  type: ss
  port: 443
- name: 🇭🇰香港 35 | @zmxooo 01 | @zmxooo
  server: 202.146.222.45
  type: ss
  port: 443
- name: 🇹🇼台湾 36 | @zmxooo 01 | @zmxooo
  server: 45.132.226.137
  type: hysteria2
  port: 443
- name: 🇹🇼台湾 37 | @zmxooo 01 | @zmxooo
  server: 45.132.226.137
  type: https
  port: 443
- name: 🇹🇼台湾 38 | @zmxooo 01 | @zmxooo
  server: 45.132.226.169
  type: hysteria2
  port: 443
- name: 🇹🇼台湾 43 | @zmxooo 01 | @zmxooo
  server: 45.132.226.137
  type: ss
  port: 443
- name: 🇬🇧英国 44 | @zmxooo 01 | @zmxooo
  server: 193.187.118.66
  type: trojan
  port: 443
- name: 🇬🇧英国 45 | @zmxooo 01 | @zmxooo
  server: 193.187.118.172
  type: trojan
  port: 443
- name: 🇬🇧英国 46 | @zmxooo 01 | @zmxooo
  server: 193.187.118.42
  type: trojan
  port: 443
- name: 🇬🇧英国 47 | @zmxooo 01 | @zmxooo
  server: 193.187.118.157
  type: trojan
  port: 443
- name: 🇬🇧英国 48 | @zmxooo 01 | @zmxooo
  server: 193.187.118.125
  type: trojan
  port: 443
- name: 🇬🇧英国 49 | @zmxooo 01 | @zmxooo
  server: 193.187.118.151
  type: trojan
  port: 443
- name: 🇹🇼台湾 54 | @zmxooo 01 | @zmxooo
  server: 45.132.226.177
  type: ss
  port: 443
- name: 🇹🇼台湾 55 | @zmxooo 01 | @zmxooo
  server: 45.132.226.161
  type: ss
  port: 443
- name: 🇹🇼台湾 56 | @zmxooo 01 | @zmxooo
  server: 45.132.226.153
  type: ss
  port: 443
- name: 🇬🇧英国 57 | @zmxooo 01 | @zmxooo
  server: 193.187.118.66
  type: trojan
  port: 443
- name: 🇹🇼台湾 63 | @zmxooo 01 | @zmxooo
  server: 45.132.226.169
  type: ss
  port: 443
