proxies:
- name: 🌍其它 zmxooo3
  server: 23.144.12.162
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo5
  server: vpn-kr-003.fastervpn.world
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: vpn-kr-003.fastervpn.world
- name: 🌍其它 zmxooo13
  server: 202.146.222.11
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo19
  server: 202.146.222.29
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo22
  server: 202.146.222.16
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo28
  server: 202.146.222.45
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo43
  server: 43.200.123.45
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo44
  server: 202.146.222.89
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo46
  server: 202.146.222.93
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo47
  server: 202.146.222.13
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo50
  server: 202.146.222.85
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo51
  server: 160.187.100.109
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
- name: 🌍其它 zmxooo52
  server: 202.146.222.41
  port: 443
  udp: true
  type: hysteria2
  password: qQe1z5kU8kN6SlKnDt9Ru3Qp
  up: 20 Mbps
  down: 100 Mbps
  skip-cert-verify: true
  sni: https://t.me/zmxooo
proxy-groups:
- name: 🌍 🚀 节点选择
  type: select
  proxies:
  - ♻️ 全局自动测速
  - 🌍 其它自动测速
  - DIRECT
- name: 🌍 其它自动测速
  type: url-test
  url: http://gstatic.com
  interval: 300
  proxies:
  - 🌍其它 zmxooo3
  - 🌍其它 zmxooo5
  - 🌍其它 zmxooo13
  - 🌍其它 zmxooo19
  - 🌍其它 zmxooo22
  - 🌍其它 zmxooo28
  - 🌍其它 zmxooo43
  - 🌍其它 zmxooo44
  - 🌍其它 zmxooo46
  - 🌍其它 zmxooo47
  - 🌍其它 zmxooo50
  - 🌍其它 zmxooo51
  - 🌍其它 zmxooo52
- name: ♻️ 全局自动测速
  type: url-test
  url: http://gstatic.com
  interval: 300
  proxies:
  - 🌍其它 zmxooo3
  - 🌍其它 zmxooo5
  - 🌍其它 zmxooo13
  - 🌍其它 zmxooo19
  - 🌍其它 zmxooo22
  - 🌍其它 zmxooo28
  - 🌍其它 zmxooo43
  - 🌍其它 zmxooo44
  - 🌍其它 zmxooo46
  - 🌍其它 zmxooo47
  - 🌍其它 zmxooo50
  - 🌍其它 zmxooo51
  - 🌍其它 zmxooo52
- name: 🚀 节点选择
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
  - 🇹🇼台湾 zmxooo1
  - 🇹🇼台湾 zmxooo2
  - 🇹🇼台湾 zmxooo3
  - 🇹🇼台湾 zmxooo4
  - 🇩🇪德国 zmxooo1
  - 🇩🇪德国 zmxooo2
  - 🇩🇪德国 zmxooo4
  - 🇩🇪德国 zmxooo5
  - 🇯🇵日本 zmxooo2
  - 🇺🇸美国 zmxooo1
  - 🇺🇸美国 zmxooo2
  - 🇺🇸美国 zmxooo3
  - 🇺🇸美国 zmxooo4
  - 🇺🇸美国 zmxooo5
  - 🇺🇸美国 zmxooo6
  - 🇺🇸美国 zmxooo8
  - 🇺🇸美国 zmxooo9
  - 🇺🇸美国 zmxooo10
  - 🇺🇸美国 zmxooo11
  - 🇺🇸美国 zmxooo12
  - 🇺🇸美国 zmxooo13
  - 🇺🇸美国 zmxooo14
  - 🇬🇧英国 zmxooo1
  - 🇬🇧英国 zmxooo2
  - 🇬🇧英国 zmxooo3
  - 🇬🇧英国 zmxooo4
  - 🇬🇧英国 zmxooo5
  - 🇬🇧英国 zmxooo6
  - 🇬🇧英国 zmxooo7
  - 🇬🇧英国 zmxooo8
  - 🇬🇧英国 zmxooo9
  - 🇬🇧英国 zmxooo10
  - 🇬🇧英国 zmxooo11
  - 🇬🇧英国 zmxooo12
  - 🇬🇧英国 zmxooo13
  - 🇻🇳越南 zmxooo1
  - 🇻🇳越南 zmxooo2
  - 🇻🇳越南 zmxooo3
  - 🇻🇳越南 zmxooo4
  - 🇻🇳越南 zmxooo5
  - 🇻🇳越南 zmxooo6
  - 🇰🇷韩国 zmxooo1
  - 🇭🇰香港 zmxooo1
  - 🇭🇰香港 zmxooo2
  - 🇭🇰香港 zmxooo3
  - 🇭🇰香港 zmxooo4
  - 🇭🇰香港 zmxooo5
  - 🇭🇰香港 zmxooo6
  - 🇭🇰香港 zmxooo7
  - 🇭🇰香港 zmxooo8
  - 🇭🇰香港 zmxooo9
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 🇹🇼台湾 zmxooo1
  - 🇹🇼台湾 zmxooo2
  - 🇹🇼台湾 zmxooo3
  - 🇹🇼台湾 zmxooo4
  - 🇩🇪德国 zmxooo1
  - 🇩🇪德国 zmxooo2
  - 🇩🇪德国 zmxooo4
  - 🇩🇪德国 zmxooo5
  - 🇯🇵日本 zmxooo2
  - 🇺🇸美国 zmxooo1
  - 🇺🇸美国 zmxooo2
  - 🇺🇸美国 zmxooo3
  - 🇺🇸美国 zmxooo4
  - 🇺🇸美国 zmxooo5
  - 🇺🇸美国 zmxooo6
  - 🇺🇸美国 zmxooo8
  - 🇺🇸美国 zmxooo9
  - 🇺🇸美国 zmxooo10
  - 🇺🇸美国 zmxooo11
  - 🇺🇸美国 zmxooo12
  - 🇺🇸美国 zmxooo13
  - 🇺🇸美国 zmxooo14
  - 🇬🇧英国 zmxooo1
  - 🇬🇧英国 zmxooo2
  - 🇬🇧英国 zmxooo3
  - 🇬🇧英国 zmxooo4
  - 🇬🇧英国 zmxooo5
  - 🇬🇧英国 zmxooo6
  - 🇬🇧英国 zmxooo7
  - 🇬🇧英国 zmxooo8
  - 🇬🇧英国 zmxooo9
  - 🇬🇧英国 zmxooo10
  - 🇬🇧英国 zmxooo11
  - 🇬🇧英国 zmxooo12
  - 🇬🇧英国 zmxooo13
  - 🇻🇳越南 zmxooo1
  - 🇻🇳越南 zmxooo2
  - 🇻🇳越南 zmxooo3
  - 🇻🇳越南 zmxooo4
  - 🇻🇳越南 zmxooo5
  - 🇻🇳越南 zmxooo6
  - 🇰🇷韩国 zmxooo1
  - 🇭🇰香港 zmxooo1
  - 🇭🇰香港 zmxooo2
  - 🇭🇰香港 zmxooo3
  - 🇭🇰香港 zmxooo4
  - 🇭🇰香港 zmxooo5
  - 🇭🇰香港 zmxooo6
  - 🇭🇰香港 zmxooo7
  - 🇭🇰香港 zmxooo8
  - 🇭🇰香港 zmxooo9
rules:
- MATCH,🚀 节点选择
